# Generated by Django 4.2.1 on 2023-05-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='sid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='sid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sms',
            name='sms',
            field=models.IntegerField(),
        ),
    ]
