# Generated by Django 4.2.1 on 2023-05-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_phone_sid_sms_sid_alter_sms_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, null=True)),
                ('approved', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='phone',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='sms',
            name='sid',
        ),
    ]
